services:
  - type: web
    name: pampatec-dashboard
    env: node
    plan: free
    rootDir: dist
    buildCommand: npm install && npm run build
    startCommand: npm run db:migrate && npm run db:seed && npm start
    envVars:
      - key: NODE_VERSION
        value: 20

